name: tryhard
description: Continue trying to run something on an interval until it succeeds or the timeout elapses.
version: 1.0.1
homepage: https://github.com/ArcaneArts/tryhard
environment:
  sdk: '>=2.18.4 <3.0.0'